### PR TITLE
Improve LogEvent timestamp logging

### PR DESCRIPTION
**Pull request by demsey**
In log events tiestamps look like  at="Fri Dec 19 14:47:44 CET 2014.86"
After the change it will look like at="Fri Dec 19 14:47:44.086 CET 2014"

### CODE REVIEW

**Comment by demsey** [comment]
Yes Date.toString() uses Locale.US, I checked it before ;)

I would be very careful when you do df as a static. SimplaDateFormat is not thread safe. (I have a bad experience when I did once df static - in production). It seems to me that LogEvent.dump() **can be called by different threads, and this will lead to disaster.**
I assumed that, multiple creation is a little slower but it works properly. I do not know how much slower.

Other ways to to deal with this problem: http://stackoverflow.com/questions/10411944/java-text-simpledateformat-not-thread-safe Will review what are the possibilities.

**Comment by ar** [comment]
Oh, good point. Will revert my change for now.

**Comment by demsey** [comment]
Maybe jast use FastDateFormat (commons-lang) instead of SimpleDateFormat?

**Comment by ar** [comment]
I prefer not to add a new dependency just for one class ...

**Comment by demsey** [comment]
I think so too;) I thought that the commons-lang is already in the jpos dependencies, but I was wrong...
I made some tests and it seems to me that newSimpleDateFormat is not so bad in this situation.
Thus it is slower but not 100 or even 10 times but 50%
```java
df.format(d);
```
This is "only" about 50% slower as above
```java
DateFormat df = new SimpleDateFormat(SOME_PATTERN);
df.format(d);
```
Here are the tests which that indicate https://github.com/demsey/jPOS/commits/logging

**Comment by ar** [comment]
Thank you for the follow-up comments and tests Robert!

**Pull request merged**
