### PR TITLE
Basic support for string array auto-configuration.

### PR DESCRIPTION
**Pull request by alcarraz**
Proposal for a basic support for autoconfiguration of string array fields. 

More complex logic could be added to support different ways of defining string arrays, or even collections of other types, in a single property, if desired, but this could do for now.

An unrelated fix for the doc is also included, that may not deserve a specific PR, and updating my mail address also.

If preferred, I can break this PR in 2 or 3.

### CODE REVIEW

**Review by ar — APPROVED** [review]

**Comment by ar** [comment]
Good PR I was about to implement. It would be great to have support for `int[]` and `long[]` as well. Will add it as time permits.

**Comment by alcarraz** [comment]
Yes, sorry.

For a property definition like this:
```xml
<property name="array" value="one two three"/>
```

Option 1 would be something like this:
```java
@Config(value="array", multi=false, separator=' ') 
```

Of course, the `multi` field could be single and have the opposite meaning, depending on what feels clearer.

Option 2:
```java
@Config(value="array", separator=" ")
```

It could also be something like this:

```java
@Config(value="array", separators=", ") //in this case the name should be plural to better indicate intention
```

It also has to be decided which should be the sane defaults.

**Comment by ar** [comment]
I don't think we want to create a DSL here. What I suggest for the time being is to support the equivalent of `cfg.getInts()` and `cfg.getLongs()`.

**Comment by alcarraz** [comment]
I was thinking about supporting the common case of space and comma separated arrays and collections, like in `CheckFields`. It's to avoid the verbosity in the configuration of having a `property` tag for each item.

**Pull request merged**
