### PR TITLE
Test against all supported versions of Java

### PR DESCRIPTION
**Pull request by jameshilliard**
Seems some tests are broken so I've disabled them for now.

### CODE REVIEW

**Comment by ar** [comment]
jPOS tests build cleanly as you can see here: https://travis-ci.org/jpos/jPOS

It makes no sense for us to disable these tests.

**Comment by jameshilliard** [comment]
> jPOS tests build cleanly as you can see here

Isn't that only building against java 8?

**Comment by ar** [comment]
We plan to support new Java versions, and actually use new Java features in a different version number. Because we have many production systems still in Java 8, we'll make a LTS support branch to support it. This is a very important decision that needs to be communicated properly to the community, agreed with the rest of the development team, etc. We can't just blindly ignore tests.

We appreciate your PR, and actually, it will help a lot to keep it around once work beings to support new Java versions, so thank you very much. For the time being, we can't accept it as-is toward `master`.

**Comment by jameshilliard** [comment]
> Because we have many production systems still in Java 8, we'll make a LTS support branch to support it.

My intention with this PR wasn't to break Java 8 compatibility but to make it run under multiple Java versions.

> We can't just blindly ignore tests.

Would this PR be acceptable if I can fix those tests to run under all Java versions?

**Pull request closed without merging**
